insert into departments(code,name) values ('67','Ingeniería Mecánica'),
   ('87','Ingeniería Mecánica');
insert into subjects(department_code,code,name) values ('67','00','Tesis de Ingeniería Mecánica'),
    ('67','01','Medios de Representación A'),
    ('67','02','Medios de Representación B'),
    ('67','03','Medios de Representación C'),
    ('67','04','Termodinámica I A'),
    ('67','05','Termodinámica'),
    ('67','06','Termodinámica y Máquinas Térmicas'),
    ('67','07','Dibujo Mecánico'),
    ('67','08','Tecnología Mecánica I'),
    ('67','09','Tecnología Mecánica II'),
    ('67','10','Calor y Termodinámica'),
    ('67','11','Mecanismos A'),
    ('67','12','Mecanismos B'),
    ('67','13','Conocimiento de Materiales I'),
    ('67','14','Conocimiento de Materiales II'),
    ('67','15','Tecnología Mecánica I'),
    ('67','16','Ensayos Industriales'),
    ('67','17','Taller'),
    ('67','18','Mecánica de Fluidos B'),
    ('67','19','Máquinas Alternativas'),
    ('67','20','Turbomáquinas'),
    ('67','21','Mediciones Físicas y Mecánicas'),
    ('67','22','Sistemas de Control'),
    ('67','23','Conversión de Energía'),
    ('67','24','Proyecto de Instalaciones Industriales'),
    ('67','25','Elem. de Máquinas'),
    ('67','26','Metrología'),
    ('67','27','Tecnol. Mecánica II'),
    ('67','28','Sistemas Hidráulicos y Neumáticos'),
    ('67','29','Proy. de Máquinas'),
    ('67','30','Combustión'),
    ('67','31','Transf. de Calor y Masa'),
    ('67','32','Tecnología del Frío'),
    ('67','33','Tecnología del Calor'),
    ('67','34','Proy. Instal. Térmicas'),
    ('67','35','Computación Aplicada'),
    ('67','36','Mecánica Aplicada'),
    ('67','37','Máquinas Energéticas'),
    ('67','38','Tecnología Mecánica B'),
    ('67','39','Dibujo para Ingenieros'),
    ('67','40','Diseño de Máq. Herram.'),
    ('67','41','Automotores'),
    ('67','42','Cont. Num. de Máq. Herram.'),
    ('67','43','Robótica Industrial'),
    ('67','44','Plantas Térmicas'),
    ('67','45','Sist. Cont. en Instal. Térm.'),
    ('67','46','Diseño Instal. Térmicas'),
    ('67','47','Metalografía'),
    ('67','48','Tratamientos Térmicos'),
    ('67','49','Metalurgia Física'),
    ('67','50','Mat.Ferrosos y sus Aplic.'),
    ('67','51','Máquinas Térmicas'),
    ('67','52','Termodinámica B'),
    ('67','53','Mecánica Computacional I'),
    ('67','54','Mecánica Computacional II A (O. Sólidos)'),
    ('67','55','Mecánica Computacional II B (O. Fluidos)'),
    ('67','56','Técnicas Energéticas'),
    ('67','57','Elem. Finitos Avanzados en la Mecánica de Fluidos'),
    ('67','58','Intr. al Método de los Elementos Finitos'),
    ('67','59','Mecánica del Continuo'),
    ('67','60','Intr. al Análisis Tensorial'),
    ('67','61','Fund. Matemáticos de la Visión en Robót.'),
    ('67','62','Elementos Finitos Avanzados'),
    ('67','64','Dibujo'),
    ('67','65','Procesos de Fabricación'),
    ('67','66','Trabajo Profesional (Or. Diseño Mecánico)'),
    ('67','67','Trabajo Profesional (Or. Termomecánica)'),
    ('67','98','Trabajo Prof. de Ing. Mecánica "A"'),
    ('67','99','Trabajo Prof. de Ing. Mecánica "B"'),
    ('87','01','Medios de Representación C'),
    ('87','02','Termodinámica I A'),
    ('87','04','Conversión de Energía'),
    ('87','05','Sistemas Hidráulicos y Neumáticos'),
    ('87','06','Mecánica Aplicada'),
    ('87','07','Fuentes y Máquinas Energéticas'),
    ('87','08','Tecnología Mecánica B'),
    ('87','09','Termodinámica y Mecánica de Fluidos'),
    ('87','10','Sistemas de Representación'),
    ('87','11','Medios de Representación A'),
    ('87','12','Mecanismos'),
    ('87','12_1015','Mecanismos'),
    ('87','13','Medios de Representación'),
    ('87','14','Termodinámica'),
    ('87','15','Taller A'),
    ('87','17','Máquinas Térmicas');
insert into departments(code,name) values ('64','Estabilidad'),
   ('84','Estabilidad');
insert into subjects(department_code,code,name) values ('64','00','Tesis de Ingeniería Civil'),
    ('64','01','Estabilidad I A'),
    ('64','02','Estabilidad II A'),
    ('64','03','Comportamiento de Materiales'),
    ('64','04','Estática y Resistenc. de Materiales A'),
    ('64','05','Estática y Resistencia de Materiales B'),
    ('64','06','Estabilidad II B'),
    ('64','07','Estabilidad III A'),
    ('64','08','Mecánica de Suelos'),
    ('64','09','Cimentaciones'),
    ('64','10','Estabilidad IV'),
    ('64','11','Estabilidad I B'),
    ('64','12','Estabilidad II B'),
    ('64','13','Estabilidad III B'),
    ('64','14','Método de los Elem.Finitos'),
    ('64','15','Estabilidad IV B'),
    ('64','16','Análisis Experimental de Tensiones'),
    ('64','17','Seguridad Estructural'),
    ('64','18','Dinámica de las Estructuras'),
    ('64','19','Dinámica de las Estructuras II'),
    ('64','20','Análisis Sísmico de Estructuras'),
    ('64','21','Estabilidad I (Estática)'),
    ('64','22','Estabilidad II (Resistencia de Materiales)'),
    ('84','00','Tesis de Ingeniería Civil'),
    ('84','01','Introducción a la Ingeniería Civil'),
    ('84','02','Estabilidad I'),
    ('84','03','Estabilidad II'),
    ('84','04','Comportamiento de materiales'),
    ('84','05','Estática y Resistencia de Materiales'),
    ('84','06','Estabilidad III'),
    ('84','07','Mecánica de Suelos y Geología'),
    ('84','08','Estabilidad IV'),
    ('84','09','Método de los Elementos Finitos'),
    ('84','10','Análisis Experimental de Tensiones'),
    ('84','11','Seguridad estructural'),
    ('84','12','Dinámica de las Estructuras'),
    ('84','13','Dinámica de las Estructuras II'),
    ('84','14','Análisis Sísmico'),
    ('84','99','Trabajo Profesional de Ingeniería Civil');
insert into departments(code,name) values ('76','Ingeniería Química');
insert into subjects(department_code,code,name) values ('76','00','Tesis de Ingeniería Química'),
    ('76','01','Introducción a la Ingeniería Química I'),
    ('76','02','Introducción a la Ingeniería Química II'),
    ('76','03','Operaciones I'),
    ('76','04','Operaciones Unitarias II'),
    ('76','05','Operaciones Unitarias III'),
    ('76','06','Ingeniería de las Instalaciones I'),
    ('76','07','Ingeniería de las Instalaciones II'),
    ('76','08','Ingeniería de la Reacciones Químicas'),
    ('76','09','Instrumen. y Control de Plantas Químicas'),
    ('76','10','Integración Industrial'),
    ('76','11','Análisis de Sistemas y Optimización'),
    ('76','12','Microbiología Industrial'),
    ('76','13','Bioingeniería Industrial'),
    ('76','15','Industria de Polímeros'),
    ('76','16','Electroquímica'),
    ('76','17','Procesos Electroquímicos'),
    ('76','18','Fisicoquímica Especial'),
    ('76','19','Procesos Fermentativos'),
    ('76','20','Ingeniería de las Reacciones Químicas II'),
    ('76','21','Simulación de Plantas Químicas'),
    ('76','22','Fundamentos de la Ing. de Reservorios'),
    ('76','23','Recuperación Asistida de Petróleo'),
    ('76','24','Fund. de la Sim. Numérica de Reservorio'),
    ('76','25','Explotación de Yacimientos'),
    ('76','26','Evaluación de Proyectos'),
    ('76','27','Control Estadístico de Procesos'),
    ('76','28','Gestión Recursos en la Ind. de Procesos'),
    ('76','29','Industria de Procesos'),
    ('76','30','Industrias Alimenticias'),
    ('76','31','Simulación de Plantas Químicas B'),
    ('76','32','Preservación de Alimentos'),
    ('76','33','Procesamiento Industrial de Alimentos'),
    ('76','40','Introducción a la Bioquímica'),
    ('76','41','Biotecnología'),
    ('76','42','Ingeniería de las Instalaciones II B'),
    ('76','43','Instrumentación y Control'),
    ('76','44','Práctica Profesional'),
    ('76','45','Termodinámica de los Procesos'),
    ('76','46','Introducción a la Ingeniería Química'),
    ('76','47','Fenómenos de Transporte'),
    ('76','48','Evaluación de Propiedades Físicas'),
    ('76','49','Operaciones Unitarias de Transferencia de Cantidad de Mov.'),
    ('76','50','Diseño de Procesos'),
    ('76','51','Introducción a la Planificación Interactiva'),
    ('76','52','Operaciones Unitarias de Transferencia de Materia'),
    ('76','53','Diseño de Reactores'),
    ('76','54','Instalaciones de Plantas de Procesos'),
    ('76','55','Microbiología Industrial'),
    ('76','56','Instrumentación y Control de Plantas Químicas'),
    ('76','57','Diseño de Procesos'),
    ('76','58','Emisiones de contaminantes químicos y biológicos'),
    ('76','59','Trabajo Profesional I'),
    ('76','60','Laboratorio de Operaciones y Procesos'),
    ('76','61','Bioingeniería'),
    ('76','62','Trabajo Profesional II'),
    ('76','63','Diseño avanzado de reactores'),
    ('76','90','Tesis de Grado de Ing. de Alimentos'),
    ('76','99','Trabajo Profesional de Ingeniería Química');
insert into departments(code,name) values ('88','Transporte'),
   ('68','Transporte');
insert into subjects(department_code,code,name) values ('68','00','Tesis de Ingeniería Civil (Transporte)'),
    ('68','01','Construcción de Carreteras'),
    ('68','02','Diseño y Oper. de Caminos'),
    ('68','03','Puertos y Vías Navegables'),
    ('68','04','Ferrocarriles'),
    ('68','05','Aeropuertos'),
    ('68','06','Transporte A'),
    ('68','07','Ingeniería del Transporte'),
    ('68','08','Planeamiento del Transporte'),
    ('68','09','Tránsito'),
    ('68','10','Ingeniería Territorial'),
    ('68','11','Ordenamiento Rural y Urbano'),
    ('68','99','Trabajo Prof. de Ing. Civil'),
    ('88','01','Construcción de Carreteras'),
    ('88','02','Diseño y Operación de Caminos'),
    ('88','03','Puertos y Vías Navegables B'),
    ('88','04','Ferrocarriles B'),
    ('88','05','Aeropuertos B'),
    ('88','06','Planeamiento del Transporte'),
    ('88','07','Tránsito'),
    ('88','08','Ingeniería Territorial'),
    ('88','09','Análisis de Sistemas de Transporte'),
    ('88','10','Caminos'),
    ('88','11','Aeropuertos A'),
    ('88','12','Ferrocarriles A'),
    ('88','13','Puertos y Vías Navegables A'),
    ('88','14','Evaluación de Proyectos');
insert into departments(code,name) values ('92','Tecnología Industrial'),
   ('72','Tecnología Industrial');
insert into subjects(department_code,code,name) values ('72','00','Tesis de Ingeniería Industrial'),
    ('72','01','Materiales Industriales I'),
    ('72','02','Industrias I'),
    ('72','03','Industrias II A'),
    ('72','04','Indust. de procesos de Conformación'),
    ('72','05','Arquitectura Industrial'),
    ('72','06','Automatización Industrial'),
    ('72','07','Industrias III'),
    ('72','08','Industrias Metalúrgicas'),
    ('72','09','Industrias Plásticas'),
    ('72','10','Industrias de Celulosa y Papel'),
    ('72','11','Industrias Petroquímicas'),
    ('72','12','Industrias Textiles'),
    ('72','13','Materiales Industriales II'),
    ('72','14','Diseño de Producto'),
    ('72','15','Industrias de la Alimentación'),
    ('72','16','Industrias II B'),
    ('72','17','Industrias Petrolíferas'),
    ('72','18','Industrias II'),
    ('72','99','Trabajo Profesional de Ing. Industrial'),
    ('92','00','Tesis de Ingeniería Industrial'),
    ('92','01','Materiales Industriales I'),
    ('92','02','Industrias I'),
    ('92','03','Introducción a la Ingeniería Industrial'),
    ('92','04','Procesos de Manufactura I'),
    ('92','05','Edificios Industriales'),
    ('92','06','Automatización Industrial y Robótica'),
    ('92','07','Instalaciones Industriales'),
    ('92','08','Diseño de Productos'),
    ('92','09','Industrias Plásticas'),
    ('92','10','Industrias de Celulosa y Papel'),
    ('92','11','Industrias Petroquímicas'),
    ('92','12','Industrias Textiles'),
    ('92','12_1018','Diseño de Productos'),
    ('92','13','Materiales Industriales II'),
    ('92','14','Seminario de Ingeniería Industrial I'),
    ('92','15','Industrias de la Alimentación'),
    ('92','16','Seminario de Ingeniería Industrial II'),
    ('92','17','Industrias Petrolíferas'),
    ('92','18','Industrias II'),
    ('92','18_862','Industrias II'),
    ('92','19','Procesos de Manufactura II'),
    ('92','20','Industria Automotríz'),
    ('92','21','Seminario de Ingeniería III'),
    ('92','99','Trabajo Profesional de Ingeniería Industrial');
insert into departments(code,name) values ('65','Electrotecnia'),
   ('85','Electrotecnia');
insert into subjects(department_code,code,name) values ('65','00','Tesis de Ingeniería Electricista'),
    ('65','01','Electrotecnia'),
    ('65','02','Introducción a Circuitos Eléctricos'),
    ('65','03','Electrotecnia General A'),
    ('65','04','Electrotecnia General B'),
    ('65','05','Electrotecnia General C'),
    ('65','06','Máquinas Eléctricas'),
    ('65','07','Mediciones Eléctricas I'),
    ('65','08','Mediciones Eléctricas II'),
    ('65','09','Teoría de Circuitos'),
    ('65','10','Teoría de Campos'),
    ('65','11','Tecnología de Materiales I'),
    ('65','12','Tecnología de Materiales II'),
    ('65','13','Teoría de Máquinas Eléctricas I'),
    ('65','14','Teoría de Máquinas Eléctricas II'),
    ('65','15','Sistemas Eléctricos de Potencia'),
    ('65','16','Transm. y Dist. de la Energía Eléctrica'),
    ('65','17','Centrales Eléctricas'),
    ('65','18','Prod. Tran. y Dis. de la Energía Eléctrica'),
    ('65','19','Instalación Eléctrica Industrial'),
    ('65','20','Calor y Electroquímica'),
    ('65','21','Accionamientos'),
    ('65','22','Aplicac. Indust. de la Energ. Eléctrica'),
    ('65','23','Construcción de Máquinas y Equipos'),
    ('65','24','Cálculos de Máquinas Eléctricas'),
    ('65','25','Construcciones Electromecánicas'),
    ('65','26','Electrónica de Potencia'),
    ('65','27','Control Avanzado y Robótica'),
    ('65','28','Control de Procesos Industriales'),
    ('65','29','Electrónica Industrial'),
    ('65','30','Electrotecnia General D'),
    ('65','31','Estaciones Transformadores'),
    ('65','32','Protecciones Eléctricas'),
    ('65','33','Economía de la Energía Eléctrica'),
    ('65','34','Luminotecnia'),
    ('65','35','Energías no convencionales'),
    ('65','36','Medidas Eléctricas'),
    ('65','37','Energías Renovables'),
    ('65','38','Medidas Eléctricas Especiales'),
    ('65','39','Metrología y Téc. de Calibración Eléct.'),
    ('65','40','Uso Eficiente de la Energía Eléctrica'),
    ('65','41','Estaciones Transform. y de Distribución'),
    ('65','42','Sistemas de Protecciones Eléctricas'),
    ('65','43','Ingeniería de las Instalaciones I'),
    ('65','44','Sistemas de Energía'),
    ('65','45','Regulación de Servicios Públicos'),
    ('65','46','Energía Eólica, Hidráulica y Marina'),
    ('65','47','Energía Solar, Geotérmica y de Biomasa'),
    ('65','48','Laboratorio de Instalaciones Eléctricas'),
    ('65','99','Trabajo Profesional de Ing. Electricista'),
    ('85','00','Tesis de Ingeniería Electricista'),
    ('85','01','Introducción a la Ingeniería Eléctrica'),
    ('85','02','Electrotecnia'),
    ('85','03','Teoría de Circuitos y Sistemas'),
    ('85','04','Campos Electromagnéticos'),
    ('85','05','Medidas Eléctricas'),
    ('85','06','Máquinas Eléctricas I'),
    ('85','07','Máquinas Eléctricas II'),
    ('85','08','Tecnología de Materiales Eléctricos'),
    ('85','09','Diagnósticos Eléctricos y Ensayos'),
    ('85','10','Construcciones Electromecánicas'),
    ('85','10_979','Construcciones Electromecánicas'),
    ('85','11','Instalaciones de Baja Tensión y Luminotecnia'),
    ('85','12','Sistemas Eléctricos de Potencia'),
    ('85','13','Centrales Eléctricas'),
    ('85','14','Transmisión y Distribución de la Energía Eléctrica'),
    ('85','15','Protecciones Eléctricas y Equipos de Maniobra'),
    ('85','16','Electrónica de Potencia'),
    ('85','17','Economía de la Energía Eléctrica'),
    ('85','18','Accionamientos'),
    ('85','19','Luminotecnia'),
    ('85','20','Energías Renovables'),
    ('85','21','Uso Eficiente de la Energía Eléctrica'),
    ('85','22','Metrología y Técnicas de Calibración Eléctrica'),
    ('85','23','Medición de Magnitudes Física por Medios Eléctricos'),
    ('85','24','Mediciones en AT'),
    ('85','25','Estaciones Transformadoras y de Distribución'),
    ('85','26','Dinámica del SEP'),
    ('85','27','Comunicaciones y Telecontrol'),
    ('85','28','Seminario de Ingeniería Electricista I'),
    ('85','29','Seminario de Ingeniería Eléctricista II'),
    ('85','30','Proyecto de Centrales Hidroeléctrica'),
    ('85','31','Proyecto de Centrales Termoeléctricas'),
    ('85','32','Proyecto de Centrales Fotovoltaicas y Eólicas'),
    ('85','33','Abastecimiento Auxiliar de la Energía Eléctrica'),
    ('85','34','Regulación de Servicios Públicos'),
    ('85','35','Electrotecnia General C'),
    ('85','36','Máquinas Eléctricas'),
    ('85','37','Laboratorio de Instalaciones Eléctricas'),
    ('85','38','Electrotecnia General'),
    ('85','40','Máquinas e Instalaciones Eléctricas'),
    ('85','54','Máquinas Eléctricas'),
    ('85','55','Laboratorio de Instalaciones Eléctricas'),
    ('85','99','Trabajo Profesional de Ingeniería Electricista');
insert into departments(code,name) values ('81','Matemática'),
   ('61','Matemática');
insert into subjects(department_code,code,name) values ('61','03','Análisis Matemático II A'),
    ('61','06','Probabilidad y Estadística A'),
    ('61','07','Matemática Discreta'),
    ('61','08','Álgebra II A'),
    ('61','09','Probabilidad y Estadística B'),
    ('61','10','Análisis Matemático III A'),
    ('61','12','Análisis Matemático III B'),
    ('61','13','Análisis Matemático III C'),
    ('61','14','Matemática Especial para Ing. Química'),
    ('61','15','Matemática Aplicada a la Agrimensura'),
    ('61','16','Matemática para Ingenieros'),
    ('61','19','Análisis Funcional'),
    ('61','22','Álgebra II C'),
    ('81','01','Análisis Matemático II'),
    ('81','02','Algebra II'),
    ('81','03','Probabilidad y Estadística A'),
    ('81','04','Probabilidad y Estadística B'),
    ('81','05','Análisis Matemático III A'),
    ('81','06','Análisis Matemático III B'),
    ('81','07','Análisis Funcional'),
    ('81','08','Análisis Matricial y Métodos Numéricos'),
    ('81','09','Probabilidad'),
    ('81','11','Matemática Discreta');
insert into departments(code,name) values ('98','Idiomas'),
   ('78','Idiomas');
insert into subjects(department_code,code,name) values ('78','01','Idioma Inglés'),
    ('78','02','Idioma Alemán'),
    ('78','03','Idioma Francés'),
    ('78','04','Idioma Italiano'),
    ('78','05','Idioma Portugués'),
    ('78','06','Inglés Técnico I'),
    ('78','07','Inglés Técnico II'),
    ('78','08','Inglés Técnico III'),
    ('78','09','Inglés Técnico IV'),
    ('98','01','Idioma Inglés'),
    ('98','02','Idioma Alemán'),
    ('98','02_1076','Idioma Alemán'),
    ('98','03','Idioma Francés'),
    ('98','03_1077','Idioma Francés'),
    ('98','04','Idioma Italiano'),
    ('98','04_1078','Idioma Italiano'),
    ('98','05','Idioma Portugués'),
    ('98','05_1079','Idioma Portugués');
insert into departments(code,name) values ('66','Electrónica'),
   ('86','Electrónica');
insert into subjects(department_code,code,name) values ('66','00','Tesis de Ingeniería Electrónica'),
    ('66','01','Técnica Digital'),
    ('66','02','Laboratorio'),
    ('66','03','Electrónica General'),
    ('66','04','Electrónica I'),
    ('66','05','Electrónica II'),
    ('66','06','Análisis de Circuitos'),
    ('66','07','Señales y Sistemas'),
    ('66','08','Circuitos Electrónicos I'),
    ('66','09','Laboratorio de Microcomputadoras'),
    ('66','10','Circuitos Electrónicos II'),
    ('66','11','Ejer. Prof. de la Ing. Electrónica'),
    ('66','12','Introducción a Proyectos'),
    ('66','14','Electrónica I'),
    ('66','15','Procesos Estocásticos'),
    ('66','16','Estructura de Datos'),
    ('66','17','Sistemas Digitales'),
    ('66','18','Teoría de Control I'),
    ('66','19','Circuitos de Pulsos'),
    ('66','20','Organiz. de Computadoras'),
    ('66','21','Comunicación de Datos'),
    ('66','22','Laboratorio de Comunicaciones I'),
    ('66','23','Teoría de las Telecomunicaciones'),
    ('66','24','Teoría de la Inf. y Codificac.'),
    ('66','25','Dispositivos Semiconductores'),
    ('66','26','Arquitecturas Paralelas'),
    ('66','27','Electrónica de Potencia'),
    ('66','28','Teoría de Control II'),
    ('66','29','Control Indust. Distribuido'),
    ('66','30','Control No Lineal'),
    ('66','31','Identif. y Control Adaptativo'),
    ('66','32','Robótica'),
    ('66','33','Laborat. de Sistemas Digitales'),
    ('66','34','Comunicaciones Digitales I'),
    ('66','35','Técnica Digital Avanzada'),
    ('66','36','Electroacústica'),
    ('66','37','Laboratorio de Comunicaciones II'),
    ('66','38','Procesamiento de Señales I'),
    ('66','39','Procesamiento de Señales II'),
    ('66','40','Sistemas de Microondas'),
    ('66','41','Televisión'),
    ('66','42','Comunicac. Digitales II'),
    ('66','43','Ing. Biomédica'),
    ('66','44','Instrumentos Electrónicos'),
    ('66','45','Laboratorio de Mediciones'),
    ('66','46','Procesamiento del Habla'),
    ('66','47','Procesam. de Imágenes'),
    ('66','48','Seminario de Electrónica_ Alvarez Hamelin'),
    ('66','48-','163 Seminario de Electrónica_ Beunza'),
    ('66','48-','475 Seminario de Electrónica_ Sinnewald'),
    ('66','48-','476 Seminario de Electrónica_ Hirchoren'),
    ('66','48-','506 Seminario de Electrónica_ Venturino'),
    ('66','48-','507 Seminario de Electrónica_ Utard'),
    ('66','48-','508 Seminario de Electrónica_ Dams'),
    ('66','48-','509 Seminario de Electrónica_ Pagola'),
    ('66','48-','510 Seminario de Electrónica_ Galarza'),
    ('66','48-','511 Seminario de Electrónica_ Ghersin'),
    ('66','48-','512 Seminario de Electrónica_ Tacca'),
    ('66','48-','513 Seminario de Electrónica_ Fernandez'),
    ('66','48-','520 Seminario de Electrónica_ Venturino'),
    ('66','48-','522 Seminario de Electrónica_ Cuervo Diaz'),
    ('66','48-','527 Seminario de Electrónica_ Tacca'),
    ('66','48-','529 Seminario de Electrónica_ España'),
    ('66','48-','531 Seminario de Electrónica_ Alberto'),
    ('66','48-','534 Seminario de Electrónica_ De La Plaza'),
    ('66','48-','549 Seminario de Electrónica_ Lipovetzky'),
    ('66','48-','551 Seminario de Electrónica_ Sellerio'),
    ('66','48-','646 Seminario de Electrónica_ Lutenberg'),
    ('66','48-','648 Seminario de Electrónica_ Galarza'),
    ('66','48-','1032 Seminario de Electrónica'),
    ('66','48-','1034 Seminario de Electrónica_ Armentano Feijoo'),
    ('66','49','Sistemas Biológicos'),
    ('66','50','Tecnol. de Componentes'),
    ('66','51','Teoría Detección y Estimación'),
    ('66','52','Laboratorio de Comunicaciones III'),
    ('66','53','Instr. y Control de Procesos'),
    ('66','54','Antenas'),
    ('66','55','Simulación de Sist. de Control'),
    ('66','56','Control Optimo'),
    ('66','57','Optoelectrónica'),
    ('66','58','Transmisión y Recepción de Comunicaciones'),
    ('66','59','Sistemas de Comunicación'),
    ('66','60','Diseño y Análisis de Vlsi'),
    ('66','61','Tecnología de Circuitos Integrados'),
    ('66','62','Redes de Computadoras'),
    ('66','63','Redes Neuronales'),
    ('66','64','Control Robusto'),
    ('66','65','Control Digital'),
    ('66','66','Seminario de Electrónica II_ Galarza'),
    ('66','66-','165 Seminario de Electrónica II_ Tacca'),
    ('66','66-','166 Seminario de Electrónica II_ Utard'),
    ('66','66-','167 Seminario de Electrónica II_ Venturino'),
    ('66','66-','276 Seminario de Electrónica II_ Dams'),
    ('66','66-','277 Seminario de Electrónica II_ Pagola'),
    ('66','66-','477 Seminario de Electrónica II_ Beunza'),
    ('66','66-','515 Seminario de Electrónica II_ Hirchoren'),
    ('66','66-','516 Seminario de Electrónica II_ Sinnewald'),
    ('66','66-','517 Seminario de Electrónica II_ Ghersin'),
    ('66','66-','518 Seminario de Electrónica II_ Fernandez'),
    ('66','66-','521 Seminario de Electrónica II_ Venturino'),
    ('66','66-','523 Seminario de Electrónica II_ Cuervo Díaz'),
    ('66','66-','526 Seminario de Electrónica II_ Alvarez Hamelin'),
    ('66','66-','528 Seminario de Electrónica II_ Tacca'),
    ('66','66-','530 Seminario de Electrónica II_ España'),
    ('66','66-','532 Seminario de Electrónica II_ Alberto'),
    ('66','66-','535 Seminario de Electrónica II_ De La Plaza'),
    ('66','66-','550 Seminario de Electrónica II_ Lipovetzky'),
    ('66','66-','552 Seminario de Electrónica II_ Sellerio'),
    ('66','66-','647 Seminario de Electrónica II_ Lutenberg'),
    ('66','66-','649 Seminario de Electrónica II_ Galarza'),
    ('66','66-','1033 Seminario de Electrónica II'),
    ('66','66-','1035 Seminario de Electrónica II_Armentano Feijoo'),
    ('66','67','Acústica'),
    ('66','68','Electroacústica'),
    ('66','69','Criptografía y Seguridad Informática'),
    ('66','70','Estructura del Computador'),
    ('66','71','Sistemas Gráficos'),
    ('66','72','Señales e Imágenes en Biomedicina'),
    ('66','73','Instal. e Instrumentación Biomédica'),
    ('66','74','Señales y Sistemas'),
    ('66','75','Procesos Estocásticos'),
    ('66','76','Transm. y Recep. de Comun'),
    ('66','77','Sistemas de Comunicac.'),
    ('66','78','Comunic. Digitales y Analógicas'),
    ('66','79','Lab. de Comunicaciones'),
    ('66','80','Sistemas Inalambricos'),
    ('66','81','Video y Redes de Cable'),
    ('66','82','Propagación y Sist. Irradiantes'),
    ('66','83','Infraestructura de Redes'),
    ('66','84','Protocolos de Accesos Inalámbricos'),
    ('66','99','Trabajo Profesional de Ing. Electrónica'),
    ('86','00','Tesis de Ingeniería Electrónica'),
    ('86','01','Técnica Digital'),
    ('86','02','Introducción a la Ingeniería Electrónica'),
    ('86','03','Dispositivos Semiconductores'),
    ('86','04','Análisis de Circuitos'),
    ('86','05','Señales y Sistemas'),
    ('86','06','Circuitos Electrónicos'),
    ('86','07','Laboratorio de Microprocesadores'),
    ('86','08','Control Automático I'),
    ('86','09','Procesos Estocásticos'),
    ('86','10','Diseño de Circuitos Electrónicos'),
    ('86','11','Teoría de la Información y la Codificación'),
    ('86','12','Comunicación de Datos'),
    ('86','13','Instrumentos Electrónicos'),
    ('86','14','Introducción a Proyectos'),
    ('86','15','Robótica'),
    ('86','16','Control Automático II'),
    ('86','17','Control Automático III'),
    ('86','18','Control Industrial Distribuido'),
    ('86','19','Control Robusto'),
    ('86','20','Identificación y Control Adaptativo'),
    ('86','21','Instrumentación y Control de Procesos'),
    ('86','22','Laboratorio de Control Automático'),
    ('86','23','Accionamientos Variables'),
    ('86','24','Electrónica de Potencia'),
    ('86','25','Comunicaciones Digitales I'),
    ('86','26','Comunicaciones Digitales II'),
    ('86','27','Infraestructura de Redes Fijas'),
    ('86','28','Laboratorio de Comunicaciones'),
    ('86','29','Propagación y Sistemas Irradiantes'),
    ('86','30','Comunicaciones Digitales III'),
    ('86','31','Servicios y Redes de Comunicaciones'),
    ('86','32','Sistemas Inalámbricos'),
    ('86','33','Electrónica'),
    ('86','34','Transmisores y Receptores de Comunicaciones'),
    ('86','35','Video Digital'),
    ('86','36','Criptografía y Seguridad Informática'),
    ('86','37','Organización de Computadoras'),
    ('86','38','Arquitecturas Paralelas'),
    ('86','39','Redes de Computadoras'),
    ('86','40','Laboratorios de Redes de Computadoras'),
    ('86','41','Sistemas Digitales'),
    ('86','42','Laboratorios de Sistemas Digitales'),
    ('86','43','Sistemas Gráficos'),
    ('86','44','Técnica Digital Avanzada'),
    ('86','45','Industrias y Productos de Electrónica'),
    ('86','46','Microelectrónica'),
    ('86','47','Optoelectrónica'),
    ('86','48','Seminario de Electrónica_Lutenberg'),
    ('86','48-','674 Seminario de Electrónica_Utard'),
    ('86','48-','714 Seminario de Electrónica_Galarza'),
    ('86','48-','715 Seminario de Electrónica_Sinnewald'),
    ('86','48-','716 Seminario de Electrónica_Cuervo Díaz'),
    ('86','48-','717 Seminario de Electrónica_Beunza'),
    ('86','48-','1030 Seminario de Electrónica_Bertolotti'),
    ('86','48-','1036 Seminario de Electrónica_Armentano Feijoo'),
    ('86','48-','1082 Seminario de Electrónica_Mas'),
    ('86','49-','Seminario de Electrónica II_Lutenberg'),
    ('86','49-','719 Seminario de Electrónica II_ Beunza'),
    ('86','49-','720 Seminario de Electrónica II_Sinnewald'),
    ('86','49-','721 Seminario de Electrónica II_Cuervo Díaz'),
    ('86','49-','722 Seminario de Electrónica II_Galarza'),
    ('86','49-','723 Seminario de Electrónica II_Utard'),
    ('86','49-','1031 Seminario de Electrónica II_Bertolotti'),
    ('86','49-','1037 Seminario de Electrónica II_Armentano Feijoo'),
    ('86','49-','1083 Seminario de Electrónica II_Mas'),
    ('86','50','Tecnología de los Componentes'),
    ('86','51','Procesamiento de Señales I'),
    ('86','52','Procesamiento de Señales II'),
    ('86','53','Procesamiento del Habla'),
    ('86','54','Redes Neuronales'),
    ('86','55','Teoría de Detección y Estimación'),
    ('86','56','Procesamiento de Imágenes'),
    ('86','57','Acústica'),
    ('86','58','Electroacústica'),
    ('86','59','Audio Profesional'),
    ('86','60','Sistemas Biológicos'),
    ('86','61','Ingeniería Biomédica'),
    ('86','62','Equipamiento para Diagnóstico y Tratamiento Biomédico'),
    ('86','63','Procesamiento y Análisis de Señales e Imágenes en Bioingeniería'),
    ('86','99','Trabajo Profesional de Ing. Electrónica');
insert into departments(code,name) values ('77','Seguridad del trabajo y ambiente'),
   ('97','Seguridad del trabajo y ambiente');
insert into subjects(department_code,code,name) values ('77','01','Higiene y Seguridad del Trabajo'),
    ('77','02','Introducción a la Ing. Ambiental'),
    ('77','05','Proyectos Nacionales e Ing. Ambiental'),
    ('77','08','Seguridad Ambiental y del Trabajo B'),
    ('77','09','Seguridad Amb. y del Trabajo A'),
    ('77','41','Gestión Ambiental en la Ind. Alim.'),
    ('97','01','Higiene y Seguridad Industrial'),
    ('97','02','Seguridad Ambiental y del Trabajo B'),
    ('97','03','Higiene y Seguridad en Obras Civiles'),
    ('97','04','Seguridad Ambiental y del Trabajo'),
    ('97','05','Gestión Ambiental');
insert into departments(code,name) values ('95','Computación'),
   ('75','Computación');
insert into subjects(department_code,code,name) values ('75','00','Tesis'),
    ('75','01','Computación'),
    ('75','02','Algoritmos y Programación I'),
    ('75','03','Organización del Computador'),
    ('75','04','Algoritmos y Programación II'),
    ('75','05','Informática II'),
    ('75','06','Organización de Datos'),
    ('75','07','Algoritmos y Programación III'),
    ('75','08','Sist. Operativos'),
    ('75','09','Análisis de la Información'),
    ('75','09_1027','Análisis de la Información'),
    ('75','10','Técnicas de Diseño'),
    ('75','11','Algoritmos y Programación'),
    ('75','12','Análisis Numérico I'),
    ('75','13','Análisis Numérico II'),
    ('75','14','Lenguajes Formales'),
    ('75','15','Base de Datos'),
    ('75','16','Lenguajes de Programación'),
    ('75','17','Implantación de Sistemas'),
    ('75','18','Proyectos Informáticos'),
    ('75','19','Teoría de Comunicación'),
    ('75','20','Arquitecturas y Configuración'),
    ('75','21','Redes y Teleprocesamientos'),
    ('75','22','Concurrencia'),
    ('75','23','Inteligencia Artificial'),
    ('75','24','Teoría de la Programación'),
    ('75','25','Computación Para Ingenieros'),
    ('75','26','Simulación'),
    ('75','27','Algoritmos y Programación IV'),
    ('75','28','Base de Datos "B"'),
    ('75','29','Teoría de Algoritmos I'),
    ('75','30','Teoría de Algoritmos II'),
    ('75','31','Teoría de Lenguaje'),
    ('75','32','Práctica Profesional'),
    ('75','33','Redes y Teleprocesamientos I'),
    ('75','34','Redes y Teleprocesamiento II'),
    ('75','35','Lenguajes Especiales'),
    ('75','36','Seminario y Lógica de Bases de Datos'),
    ('75','37','Laboratorio de Programación de Base'),
    ('75','38','Análisis Numérico II A'),
    ('75','39','Aplicaciones Informáticas'),
    ('75','40','Algoritmos y Programación I'),
    ('75','40-','544 Algoritmos y Programación I_ Wachenchauzer'),
    ('75','41','Algoritmos y Programación II'),
    ('75','41-','533 Algoritmos y Programación II_ Wachenchauzer'),
    ('75','41-','1061 Algoritmos y Programación II_ Carolo'),
    ('75','42','Taller de Programación I'),
    ('75','43','Introd. a los Sistemas Distribuidos'),
    ('75','44','Admin. y Control de Proyectos Inform. I'),
    ('75','45','Taller de Desarrollo de Proyectos I'),
    ('75','46','Administración y Control de Proyectos Informáticos II'),
    ('75','47','Taller de Desarrollo de Proyectos II'),
    ('75','48','Calidad en Desarrollo de Sistemas'),
    ('75','50','Introd. a los Sistemas Inteligentes'),
    ('75','51','Técnicas de Producción de Software I'),
    ('75','52','Taller de Programación II'),
    ('75','53','Técnicas de Producción de Software II'),
    ('75','54','Técnicas de Producción de Software III'),
    ('75','55','Taller de Desarrollo de Proyectos III'),
    ('75','56','Organiz. Implant. y el Mantenimiento'),
    ('75','57','Modelos de Proceso de Desarrollo'),
    ('75','58','Evaluación de Proy. y Manejo de Riesgos'),
    ('75','59','Técnicas de Programac. Concurrente I'),
    ('75','60','Sistemas Distribuidos I'),
    ('75','61','Taller de Programación III'),
    ('75','62','Técnicas de Programac. Concurrente II'),
    ('75','63','Sistemas Distribuidos II'),
    ('75','64','Sistemas Multimediales'),
    ('75','65','Manuf. Integrada p/ Comput. (CIM) I'),
    ('75','66','Manuf. Integrada p/ Comput. (CIM) II'),
    ('75','67','Sist. Aut. de Diag. y Detección Fallas I'),
    ('75','68','Sist. de Soporte p/ Celdas Prod. Flexible'),
    ('75','69','Sist. Aut. de Diag. y Detección Fallas II'),
    ('75','70','Sist. de Prog. no convencional de Robots'),
    ('75','71-','460 Seminario_ Zelasco'),
    ('75','71','Seminario_ Cosso'),
    ('75','72','Seminario de Ing. en Informática II'),
    ('75','73','Arquitectura de Software'),
    ('75','74','Sistemas Distribuidos I'),
    ('75','75','Computación I'),
    ('75','76','Computación II'),
    ('75','99','Trabajo Profesional'),
    ('95','01','Computación'),
    ('95','02','Algoritmos y Programación III'),
    ('95','03','Sistemas Operativos'),
    ('95','04','Análisis Numérico I'),
    ('95','05','Base de Datos'),
    ('95','06','Teoría de Algoritmos I'),
    ('95','07','Teoría del Lenguaje'),
    ('95','08','Taller de Programación I'),
    ('95','09','Técnicas de Programación Concurrente I'),
    ('95','10','Modelación Numérica'),
    ('95','11','Algoritmos y Programación I'),
    ('95','12','Algoritmos y Programación II'),
    ('95','13','Métodos Matemáticos y Numéricos'),
    ('95','14','Algoritmos y Programación I'),
    ('95','14-1064','Algoritmos y Programación I_ Wachenchauzer'),
    ('95','15','Algoritmos y Programación II_Wachenchauzer'),
    ('95','15-','1062 Algoritmos y Programación II_Calvo'),
    ('95','15-','1063 Algoritmos y Programación II_Carolo'),
    ('95','19','Simulación'),
    ('95','20','Métodos y Modelos en la Ingeniería del Software I'),
    ('95','21','Métodos y Modelos en la Ingeniería del Software II'),
    ('95','24','Administración y Control de Proyectos Informáticos I'),
    ('95','25','Inteligencia Artificial'),
    ('95','30','Estándares de Calidad y Modelos de Referencia'),
    ('95','48','Lenguajes Formales'),
    ('95','49','Lenguajes de Programación'),
    ('95','57','Organización del Computador'),
    ('95','58','Organización del Datos'),
    ('95','59','Diseño, Operación y Gestión de Servicios Informáticos'),
    ('95','60','Redes y Aplicaciones Distribuidas'),
    ('95','61','Trabajo Profesional de Licenciatura en Análisis de Sistemas'),
    ('95','67','Minería de Datos'),
    ('95','68','Desarrollo con Nuevas Tecnologías');
insert into departments(code,name) values ('74','Construcciones y Estructuras'),
   ('94','Construcciones y Estructuras');
insert into subjects(department_code,code,name) values ('74','01','Hormigón I'),
    ('74','02','Mecánica de Suelos'),
    ('74','03','Arquitectura y Planificación'),
    ('74','04','Construcciones'),
    ('74','05','Hormigón II'),
    ('74','06','Tecnología del Hormigón'),
    ('74','07','Instalaciones de Edificios'),
    ('74','08','Presas'),
    ('74','09','Maquinarias de la Construcción'),
    ('74','10','Urbanismo'),
    ('74','11','Cimentaciones'),
    ('74','12','Estructuras Metálicas I'),
    ('74','13','Estructuras Metálicas II'),
    ('74','14','Tecnología del Hormigón'),
    ('74','15','Patología de la Construcción'),
    ('74','16','Estructuras de Madera'),
    ('74','17','Sistemas Constructivos'),
    ('74','18','Sistemas Estructurales'),
    ('74','19','Diseño Estructural'),
    ('74','20','Ejecución de Estructuras de Hormigón'),
    ('74','21','Inspección y Ejecución de Estructuras de Hormigón'),
    ('74','99','Trabajo Prof. de Ing. Civil'),
    ('94','01','Hormigón I'),
    ('94','02','Arquitectura y Planificación Urbana'),
    ('94','03','Construcciones'),
    ('94','04','Hormigón II'),
    ('94','05','Instalaciones en Obras Civiles I'),
    ('94','06','Presas'),
    ('94','07','Maquinarias de la Construcción'),
    ('94','08','Urbanismo'),
    ('94','09','Geotécnica Aplicada'),
    ('94','10','Estructuras Metálicas I'),
    ('94','11','Estructuras Metálicas II'),
    ('94','12','Tecnología del Hormigón'),
    ('94','13','Patología de la Construcción'),
    ('94','14','Estructuras de Madera'),
    ('94','15','Sistemas Constructivos'),
    ('94','16','Sistemas Estructurales'),
    ('94','17','Diseño Estructural'),
    ('94','18','Inspección y Ejecución de Estructuras de Hormigón'),
    ('94','19','Materiales No Tradicionales en la Construcción'),
    ('94','20','Instalaciones en Obras Civiles II');
insert into departments(code,name) values ('93','Ingeniería Naval'),
   ('73','Ingeniería Naval');
insert into subjects(department_code,code,name) values ('73','00','Tesis de Ingeniería Naval'),
    ('73','01','Arquitectura Naval I'),
    ('73','02','Construcción Naval I'),
    ('73','03','Arquitectura Naval II'),
    ('73','04','Estructura de Buques'),
    ('73','05','Introducción a Máquinas Marinas'),
    ('73','06','Vibraciones de Estructuras'),
    ('73','07','Construcción Naval II'),
    ('73','08','Estructura de Buques II'),
    ('73','09','Proyecto de Buques I'),
    ('73','10','Proyecto de Buques II'),
    ('73','11','Máquinas Marinas I'),
    ('73','12','Máquinas Marinas II'),
    ('73','13','Construcción Naval III'),
    ('73','14','Navegación'),
    ('73','15','Máquinas Marinas III'),
    ('73','16','Construcción Naval III'),
    ('73','40','Prácticas en Astilleros I'),
    ('73','41','Prácticas en Astilleros II'),
    ('73','51','Álgebra'),
    ('73','52','Métodos Estadísticos'),
    ('73','53','Análisis I'),
    ('73','54','Análisis I'),
    ('73','55','Química General I'),
    ('73','56','Química Aplicada'),
    ('73','57','Materiales'),
    ('73','58','Dibujo'),
    ('73','59','Estabilidad I (Estática)'),
    ('73','60','Estabilidad II (Resistencia de Materiales)'),
    ('73','61','Organización de la Producción Naval'),
    ('73','62','Física I (Mecánica)'),
    ('73','63','Física II (Calor)'),
    ('73','64','Física III (Electricidad)'),
    ('73','65','Física IV (Hidráulica)'),
    ('73','66','Construcción Naval Mercante I'),
    ('73','67','Construcción Naval Mercante II'),
    ('73','68','Normas y Reglamentos'),
    ('73','69','Arquitectura Naval'),
    ('73','70','Computación'),
    ('73','71','Relaciones Humanas'),
    ('73','72','Inglés I'),
    ('73','73','Inglés II'),
    ('73','74','Inglés III'),
    ('73','75','Inglés IV'),
    ('73','76','Alemán I'),
    ('73','77','Alemán II'),
    ('73','78','Soldadura'),
    ('73','79','Mecanizado'),
    ('73','80','Calderería'),
    ('73','81','Electricidad'),
    ('73','82','Aislamiento'),
    ('73','83','Motores principales y propulsión'),
    ('73','84','Pintura'),
    ('73','85','Montaje Mecánico'),
    ('73','86','Gestión de garantía de Calidad'),
    ('73','87','Gestión de Producción'),
    ('73','88','Arquitectura Naval II'),
    ('73','89','Máquinas e Instalaciones Auxiliares Navales'),
    ('73','90','Máquinas e Instalaciones Eléctricas Navales'),
    ('73','91','Máquinas e Instalaciones Propulsoras Navales'),
    ('73','92','Taller V: Casco y Alistamiento: Reparación'),
    ('73','93','Taller VI: Casco y Alistamiento: Construcción'),
    ('73','94','Taller VII: Propulsión'),
    ('73','95','Proyecto Integrador'),
    ('73','96','Dibujo Naval'),
    ('73','97','Arquitectura Naval I'),
    ('73','98','Taller I: Electricidad'),
    ('73','99','Trabajo Profes. de Ing. Naval y Mec.'),
    ('93','01','Taller II: Pintura'),
    ('93','02','Taller III: Soldadura'),
    ('93','03','Taller IV: Gestión de Garantía de Calidad'),
    ('93','04','Taller VIII: Gestión de Producción');
insert into departments(code,name) values ('62','Física'),
   ('82','Física');
insert into subjects(department_code,code,name) values ('62','01','Física I A'),
    ('62','02','Física I B'),
    ('62','03','Física II A'),
    ('62','04','Física II B'),
    ('62','05','Fisica III'),
    ('62','06','Mecánica I'),
    ('62','07','Mecánica II'),
    ('62','08','Electromagnetismo A'),
    ('62','09','Electromagnetismo B'),
    ('62','10','Física del Estado Sólido'),
    ('62','11','Mecánica Racional'),
    ('62','13','Física III C'),
    ('62','15','Física III D'),
    ('62','18','Física de Fluidos'),
    ('62','20','Física I (Mecánica)'),
    ('62','21','Física II (Calor)'),
    ('62','22','Física III (Electricidad)'),
    ('62','23','Física IV (Hidráulica)'),
    ('82','01','Física I'),
    ('82','02','Física II'),
    ('82','03','Física III'),
    ('82','04','Mecánica Racional'),
    ('82','05','Física del Estado Sólido'),
    ('82','06','Electromagnetismo'),
    ('82','07','Física III B'),
    ('82','11','Mecánica Racional'),
    ('82','50','Física del Estado Sólido');
insert into departments(code,name) values ('91','Gestión'),
   ('71','Gestión');
insert into subjects(department_code,code,name) values ('71','01','Intr. a la Econom. y Org. de la Empresa'),
    ('71','02','Agrimensura Legal I'),
    ('71','03','Estadística Técnica'),
    ('71','04','Organización Industrial I'),
    ('71','05','Organización Industrial II'),
    ('71','06','Estructura Económica Argentina'),
    ('71','07','Investigación Operativa'),
    ('71','08','Organización Industrial III'),
    ('71','09','Economía de la Empresa'),
    ('71','10','Economía General'),
    ('71','11','Organización de Obras'),
    ('71','12','Estructura de las Organizaciones'),
    ('71','13','Información en las Organizaciones'),
    ('71','14','Modelos y Optimización I'),
    ('71','15','Modelos y Optimización II'),
    ('71','16','Administración de Proyectos'),
    ('71','17','Derecho Informático'),
    ('71','18','Estructura Económica Argentina'),
    ('71','19','Economía de las Organizaciones'),
    ('71','20','Modelos y Optimización III'),
    ('71','21','Leg. y Ejer. Prof. de la Ing. Civil'),
    ('71','22','Leg. y Ejer. Prof. de la Ing. Industrial'),
    ('71','23','Economía'),
    ('71','24','Agrimensura Legal II'),
    ('71','25','Leg. y Ejer. Prof. de la Ing. Mecánica'),
    ('71','26','Leg. y Ejerc. Prof. de la Ing. Electricista'),
    ('71','27','Leg. y Ejer. Prof. de la Ing. Electrónica'),
    ('71','28','Leg. y Ejer. Prof. de la Ing. Química'),
    ('71','30','Agrimensura Legal III'),
    ('71','31','Organización de la Producción'),
    ('71','32','Investigación Operativa Superior'),
    ('71','33','Comercializ. de Productos Industriales'),
    ('71','34','Gestión Presupuestaria'),
    ('71','35','Estadística Técnica Superior'),
    ('71','36','Gestión de Calidad'),
    ('71','37','Dirección de Manufactura'),
    ('71','38','Legislación General'),
    ('71','39','Leg. y Ejer. Prof. de la Ing. Electric. B'),
    ('71','40','Legislación y Ejercicio Profesional de la Ingeniería en Info'),
    ('71','41','Análisis y Resol. de Probl.'),
    ('71','42','Circuitos de Información en la Empresa'),
    ('71','43','Logística Integral'),
    ('71','44','Recursos Humanos'),
    ('71','45','Informática p/la Gestión de Empresas'),
    ('71','46','Ingeniería Económica'),
    ('71','49','Recursos Humanos'),
    ('71','50','Ingeniería Económica I'),
    ('71','51','Ingeniería Económica II'),
    ('71','52','Agrimensura Legal IV'),
    ('71','53','Evaluación de Proyectos de Plantas Químicas'),
    ('71','55','Economía de la Empresa Alimentaria'),
    ('71','56','Legislación y Ejercicio Profesional de la Ing. de Alimentos'),
    ('71','57','Métodos Cuantitativos Aplicados en Sistemas Agroalimentarios'),
    ('71','58','Análisis y Resol. de Probl. de Sistemas'),
    ('71','59','Emprendimientos en Ingeniería'),
    ('71','60','Relaciones Humanas'),
    ('71','61','Organización de la Producción Naval'),
    ('71','62','Legislación Comercial y Laboral'),
    ('91','02','Gerenciamiento y Organización de Obras Civiles'),
    ('91','03','Estadística Aplicada I'),
    ('91','04','Modelos y Optimización I'),
    ('91','05','Modelos y Optimización II'),
    ('91','06','Modelos y Optimización III'),
    ('91','07','Investigación Operativa I'),
    ('91','08','Organización Industrial III'),
    ('91','09','Economía'),
    ('91','10','Organización Industrial I'),
    ('91','11','Legislación y Ejercicio Profesional de la Ing. Electrónica'),
    ('91','12','Organización Industrial II'),
    ('91','13','Organización de la Producción'),
    ('91','14','Informática para Gestión de Empresas'),
    ('91','15','Legislación y Ejercicio Profesional de la Ingeniería Electr.'),
    ('91','16','Legislación y Ejercicio Profesional de la Ingeniería Civil'),
    ('91','17','Recursos Humanos'),
    ('91','18','Ingeniería Económica'),
    ('91','19','Introducción a la Economía y Organización de la Empresa'),
    ('91','20','Comercialización'),
    ('91','21','Conflicto y Negociación'),
    ('91','22_1017','Comercialización'),
    ('91','22','Ingeniería Legal para Ingeniería Industrial'),
    ('91','24','Macroeconomía y Estructura Económica Argentina'),
    ('91','25','Estadística Aplicada III'),
    ('91','26','Dirección de Manufactura'),
    ('91','27','Logística'),
    ('91','28','Gestión de Costos'),
    ('91','29','Ingeniería Económica A'),
    ('91','30','Estadística Aplicada II'),
    ('91','31','Investigación Operativa II'),
    ('91','32','Investigación Operativa III'),
    ('91','33','Microeconomía Aplicada'),
    ('91','34','Gestión Financiera'),
    ('91','35','Análisis de Casos'),
    ('91','36','Gestión de Calidad'),
    ('91','37','Emprendimientos en Ingeniería'),
    ('91','39','Estructuras y Procesos Organizacionales'),
    ('91','40','Legislación y Ejercicio Profesional en Sistemas e Informática'),
    ('91','41','Economía de las Organizaciones'),
    ('91','42','Administración de las Organizaciones');
insert into departments(code,name) values ('70','Agrimensura'),
   ('90','Agrimensura');
insert into subjects(department_code,code,name) values ('70','00','Tesis'),
    ('70','01','Geometría Proyectiva'),
    ('70','02','Geometría Descriptiva'),
    ('70','03','Medios de Representación A'),
    ('70','04','Dibujo Topográfico'),
    ('70','05','Topografía I'),
    ('70','06','Geografía Física y Geología'),
    ('70','07','Cálculo de Compensación'),
    ('70','08','Topografía I'),
    ('70','09','Topografía II'),
    ('70','10','Mediciones con instrumental electrónico'),
    ('70','11','Topografía III'),
    ('70','12','Geodesia I'),
    ('70','13','Geodesia II'),
    ('70','14','Fotogrametría I'),
    ('70','15','Cartografía'),
    ('70','16','Fotogrametría II'),
    ('70','17','Geodesia III'),
    ('70','18','Catastro y Valuaciones'),
    ('70','19','Levantamiento y Práctica Prof.'),
    ('70','20','Fotointerpretación'),
    ('70','21','Información rural y colonización'),
    ('70','22','Ordenamiento rural y urbano'),
    ('70','23','Microgeodesia'),
    ('70','24','Levantamientos Hidrográficos'),
    ('70','25','Levantamientos Subterráneos'),
    ('70','26','Hidráulica Agrícola y Saneamiento'),
    ('70','27','Catastro'),
    ('70','28','Tasaciones y Valuaciones'),
    ('70','29','Topografía y Geodesia'),
    ('70','30','Introd. a los Sist. de Inform. Geográfica'),
    ('70','31','Información Rural'),
    ('70','32','Sistemas de Información Geográfica'),
    ('70','33','Elementos de Construcción'),
    ('70','34','Topografía III'),
    ('70','35','Topografía IV'),
    ('70','36','Sistemas Cartográficos y Teledetección'),
    ('70','37','Levantamiento y Práctica Profesional I'),
    ('70','38','Levantamiento y Práctica Profesional II'),
    ('70','39','Valuaciones'),
    ('70','40','Geología Aplicada'),
    ('70','41','Oceanografía Física'),
    ('70','42','Sistemas de Información Geográfica II'),
    ('70','43','Topografía De Obra'),
    ('70','44','Dibujo Topográfico II'),
    ('70','99','Trabajo Profesional de la Ingeniería en Agrimensura'),
    ('90','01','Topografía y Geodesia');
insert into departments(code,name) values ('69','Hidráulica'),
   ('89','Hidráulica');
insert into subjects(department_code,code,name) values ('69','00','Tesis de Ingeniería Civil (Hidráulica)'),
    ('69','01','Hidráulica General'),
    ('69','02','Ingeniería Sanitaria'),
    ('69','03','Mecánica de los Fluidos A'),
    ('69','04','Hidráulica Aplicada'),
    ('69','05','Centrales Hidráulicas'),
    ('69','06','Modelos Hidráulicos'),
    ('69','07','Hidrología'),
    ('69','08','Planific. de Recursos Hidráulicos'),
    ('69','09','Hidráulica Fluvial y Marítima'),
    ('69','10','Construcciones Hidráulicas'),
    ('69','11','Gestión Ambiental de los Recursos Hídricos'),
    ('69','99','Trabajo Prof. de Ing. Civil'),
    ('89','01','Hidráulica General'),
    ('89','03','Centrales Hidráulicas'),
    ('89','04','Modelos Hidráulicos'),
    ('89','05','Hidrología'),
    ('89','06','Planificación de Recursos Hidráulicos'),
    ('89','07','Construcciones Hidráulicas'),
    ('89','08','Gestión Ambiental de Recursos Hídricos'),
    ('89','09','Hidráulica Aplicada'),
    ('89','10','Aprovechamientos Hidráulicos'),
    ('89','11','Ingeniería Sanitaria I'),
    ('89','12','Gestión Ambiental en Ingeniería Civil'),
    ('89','13','Hidráulica Fluvial'),
    ('89','14','Hidráulica Marítima'),
    ('89','15','Laboratorio de Hidráulica'),
    ('89','16','Ingeniería Sanitaria II'),
    ('89','17','Mecánica de los Fluidos');
insert into departments(code,name) values ('63','Química'),
   ('83','Química');
insert into subjects(department_code,code,name) values ('63','01','Química'),
    ('63','02','Química I'),
    ('63','03','Química II'),
    ('63','04','Química III'),
    ('63','05','Química Analítica'),
    ('63','06','Química Física I'),
    ('63','07','Química Física II'),
    ('63','08','Análisis Instrumental'),
    ('63','09','Química Orgánica Especial'),
    ('63','10','Termodinámica Estadística'),
    ('63','11','Química Aplicada A'),
    ('63','12','Metodología y Aplicación de Radioisótopos'),
    ('63','13','Química Inorgánica'),
    ('63','14','Química Orgánica'),
    ('63','15','Química Analítica Instrumental'),
    ('63','16','Química Física'),
    ('63','18','Química General'),
    ('63','19','Química Aplicada'),
    ('83','01','Química'),
    ('83','02','Química Aplicada'),
    ('83','04','Química del Petróleo');
